# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dis.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 300)
        Form.setStyleSheet("QWidget {\n"
"                    background : #1b1716;\n"
"                    color: #f3f7fb;\n"
"                }\n"
"                QPushButton {\n"
"                    background : #1f5d2f;\n"
"                    border-radius: 3px; \n"
"                }\n"
"                QListWidget{\n"
"                    background : #25252a;\n"
"                    font-size: 13px;\n"
"                }\n"
"                QSlider{\n"
"                    color : #1f5d2f;\n"
"                }\n"
"                QSlider::groove:horizontal {  \n"
"                    height: 10px;\n"
"                    margin: 0px;\n"
"                    border-radius: 5px;\n"
"                    background: #B0AEB1;\n"
"                }\n"
"                QSlider::handle:horizontal {\n"
"                    background: #fff;\n"
"                    border: 1px solid #E3DEE2;\n"
"                    width: 17px;\n"
"                    margin: -5px 0; \n"
"                    border-radius: 8px;\n"
"                }\n"
"                QSlider::sub-page:qlineargradient {\n"
"                    background: #3B99FC;\n"
"                    border-radius: 5px;\n"
"                }")
        self.lw = QtWidgets.QListWidget(Form)
        self.lw.setGeometry(QtCore.QRect(0, 0, 280, 300))
        self.lw.setObjectName("lw")
        self.lb1 = QtWidgets.QLabel(Form)
        self.lb1.setGeometry(QtCore.QRect(289, 160, 41, 50))
        self.lb1.setObjectName("lb1")
        self.qsl = QtWidgets.QSlider(Form)
        self.qsl.setGeometry(QtCore.QRect(330, 170, 370, 30))
        self.qsl.setOrientation(QtCore.Qt.Horizontal)
        self.qsl.setObjectName("qsl")
        self.btn_play = QtWidgets.QPushButton(Form)
        self.btn_play.setGeometry(QtCore.QRect(460, 210, 75, 41))
        self.btn_play.setObjectName("btn_play")
        self.btn_preview = QtWidgets.QPushButton(Form)
        self.btn_preview.setGeometry(QtCore.QRect(380, 210, 75, 41))
        self.btn_preview.setObjectName("btn_preview")
        self.btn_next = QtWidgets.QPushButton(Form)
        self.btn_next.setGeometry(QtCore.QRect(540, 210, 75, 41))
        self.btn_next.setToolTip("")
        self.btn_next.setObjectName("btn_next")
        self.lb2 = QtWidgets.QLabel(Form)
        self.lb2.setGeometry(QtCore.QRect(709, 160, 41, 50))
        self.lb2.setObjectName("lb2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 260, 451, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_openmusic = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_openmusic.setObjectName("btn_openmusic")
        self.horizontalLayout.addWidget(self.btn_openmusic)
        self.cmb = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cmb.setObjectName("cmb")
        self.horizontalLayout.addWidget(self.cmb)
        self.pixlbl = QtWidgets.QLabel(Form)
        self.pixlbl.setGeometry(QtCore.QRect(280, 0, 470, 151))
        self.pixlbl.setText("")
        self.pixlbl.setObjectName("pixlbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb1.setText(_translate("Form", "00:00"))
        self.btn_play.setText(_translate("Form", "Play ►"))
        self.btn_preview.setText(_translate("Form", "⏪"))
        self.btn_next.setText(_translate("Form", "⏩"))
        self.lb2.setText(_translate("Form", "00:00"))
        self.btn_openmusic.setText(_translate("Form", "Выбрать папку с музыкой"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
